import { TextEdit , VerticalBox,Button, GroupBox, HorizontalBox} from "std-widgets.slint";
export component Example inherits Window {
    background: #131516;
    width: 1080px;
    height: 400px;

    in-out property <string> code: "//hello world! I'm Krusty the Krab and i like money lol. \n \n//Insert your rusty code over here and i will do the rest\n \n//Also,I tell NO to code that asks input from user \n \n \nfn main(){\n     //write code here\n}";
    out property <string> stderr: "//Compile time warnings \n \n let him start cooking!!";
    out property <string> stdout : "//Your output over here \n \n Write some code first, Krusty is starting to feel bored";

    callback compile-code-rs(string,string,string);


    VerticalBox {
        alignment: center;
        padding: 10px;
        spacing: 10px;

        MainCode := TextEdit {
            font-size: 18px;
            width: 80%;
            height: 300px;
            text: code;
        }
        
        CompileButton := Button {
            padding: 10px;
            width: 500px;
            height: 40px;
            text: "let him cook (compile code)";
            primary: true;
            clicked => { 
                //compile code logic
                self.text = "Compiling";
                self.primary = !self.primary;
                stderr = "He is cooking, wait patiently...!";
                stdout = "Wait until he brings the meal...";
                // compile_code_rs(MainCode.text,StdErr.text,StdOut.text);
                self.text = "Compiled";
             }
        }
        
        OutputSection := HorizontalBox {
            padding: 10px;
            
            StdErr := TextEdit {
                read-only: true;
                font-size: 18px;
                width: 50%;
                height: 250px;
                text: stderr;
                
            }

            StdOut := TextEdit {
                read-only: true;
                font-size: 18px;
                width: 50%;
                height: 250px;
                text: stdout;
            }
        }
        

    }
}    
