import { TextEdit , VerticalBox,Button, GroupBox, HorizontalBox} from "std-widgets.slint";

component MainCodeEditor {
    
}

component CompileTimeWarnings {
    
}

component CompileButton {
    
}

component ResultCompiled {
    
}


export component Example inherits Window {
    background: #131516;
    width: 1080px;
    height: 690px;

    in-out property <string> code: "//hello world! I'm Krusty the Krab and i like money lol. \n \n//Insert your rusty code over here and i will do the rest\n \n//Also,I tell NO to code that asks input from user \n \n \nfn main(){\n     //write code here\n}";
    out property <string> warnings : "//Compile time warnings \n \n let him start cooking!!";
    out property <string> result : "//Your output over here \n \n Write some code first, Krusty is starting to feel bored";

    callback compile-code-rs(string,string,string);


    VerticalBox {
        alignment: center;
        padding: 10px;
        spacing: 10px;

        MainCode := TextEdit {
            font-size: 21px;
            width: parent.width;
            height: 400px;
            text: code;
        }
        
        CompileButton := Button {
            padding: 10px;
            width: 500px;
            height: 40px;
            text: "let him cook (compile code)";
            primary: true;
            clicked => { 
                //compile code logic
                self.text = "Compiled";
                self.primary = !self.primary;
                compile_code_rs(MainCode.text,Warnings.text,Result.text);
    
             }
        }
        
        HorizontalBox {
            padding: 10px;
            
            Warnings := TextEdit {
                read-only: true;
                font-size: 18px;
                width: 50%;
                height: 250px;
                text: warnings;
                
            }

            Result := TextEdit {
                read-only: true;
                font-size: 18px;
                width: 50%;
                height: 250px;
                text: result;
            }
        }
        

    }
}    

